[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --no-stub --chip esp32s2 --port /dev/tty.usbmodem01 --after watchdog-reset"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["core"]
